# Data cleaning

## Import required libraries

In [1]:
import pandas as pd
from pathlib import Path

## Load the dataset

In [2]:
DATA_PATH = Path("../data/raw/train.csv")

df = pd.read_csv(DATA_PATH)

## Convert `Order Date` and `Ship Date` to pandas datetime format

In [3]:
df['Order Date'] = pd.to_datetime(df['Order Date'], format='%d/%m/%Y')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format='%d/%m/%Y')

## Sorting data by order date and setting the index

In [5]:
df.drop('Row ID', axis=1, inplace=True)
df.sort_values(by=['Order Date'], inplace=True, ascending=True)
df.set_index('Order Date', inplace=True)

## Filling null values in `Postal Code`

In [6]:
df[df['Postal Code'].isnull()]

,Order ID,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Order Date,,,,,,,,,,,,,,,,
2016-11-07,CA-2016-162887,2016-11-09,Second Class,SV-20785,Stewart Visinsky,Consumer,United States,Burlington,Vermont,NaN,East,FUR-CH-10000595,Furniture,Chairs,Safco Contoured Stacking Chairs,715.20
2016-11-08,CA-2016-117086,2016-11-12,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.90
2017-01-23,US-2017-165505,2017-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10002926,Technology,Accessories,Logitech Wireless Marathon Mouse M705,99.98
2017-01-23,US-2017-165505,2017-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-ST-10001526,Office Supplies,Storage,Iceberg Mobile Mega Data/Printer Cart,1564.29
2017-01-23,US-2017-165505,2017-01-27,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-AR-10003477,Office Supplies,Art,4009 Highlighters,8.04
2017-04-06,US-2017-150140,2017-04-10,Standard Class,VM-21685,Valerie Mitchum,Home Office,United States,Burlington,Vermont,NaN,East,TEC-PH-10002555,Technology,Phones,Nortel Meridian M5316 Digital phone,1294.75
2018-01-19,US-2018-127292,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-AP-10000828,Office Supplies,Appliances,Avanti 4.4 Cu. Ft. Refrigerator,542.94
2018-01-19,US-2018-127292,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,2.04
2018-01-19,US-2018-127292,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,12.28
2018-01-19,US-2018-127292,2018-01-23,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10000157,Office Supplies,Paper,Xerox 191,79.92
2018-12-05,CA-2018-104066,2018-12-10,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10001013,Technology,Accessories,Logitech ClearChat Comfort/USB Headset H390,205.03

All missing values were found in the Postal Code column and corresponded to orders from Burlington, Vermont. Since the missing records shared the same geographic information, the postal code was filled with the appropriate value for that location.
Postal Code for Burlington (US) is 05401.

In [11]:
df['Postal Code'] = df['Postal Code'].fillna(5401)

## Check data types and missing values¶

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9800 entries, 2015-01-03 to 2018-12-30
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       9800 non-null   object
 1   Ship Date      9800 non-null   datetime64[ns]
 2   Ship Mode      9800 non-null   object
 3   Customer ID    9800 non-null   object
 4   Customer Name  9800 non-null   object
 5   Segment        9800 non-null   object
 6   Country        9800 non-null   object
 7   City           9800 non-null   object
 8   State          9800 non-null   object
 9   Postal Code    9800 non-null   float64
 10  Region         9800 non-null   object
 11  Product ID     9800 non-null   object
 12  Category       9800 non-null   object
 13  Sub-Category   9800 non-null   object
 14  Product Name   9800 non-null   object
 15  Sales          9800 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(13)
memory usage: 1.3+ MB

## Detect potential outliers in the `Sales` column

To identify unusually high or low sales values, the Interquartile Range (IQR) method is applied.

The lower and upper bounds are calculated as:

- Lower bound = Q1 − 1.5 × IQR
- Upper bound = Q3 + 1.5 × IQR

Transactions outside these bounds are considered potential outliers and will be reviewed to determine whether they are data errors or legitimate high-value sales.

In [19]:
Q1 = df["Sales"].quantile(0.25)
Q3 = df["Sales"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

In [31]:
outliers = df[(df["Sales"] < lower) | (df["Sales"] > upper)]

print(f"Number of outliers: {len(outliers)}")
outliers = outliers.sort_values(by='Sales', ascending=False)
outliers.head()

Number of outliers: 1145

,Order ID,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
Order Date,,,,,,,,,,,,,,,,
2015-03-18,CA-2015-145317,2015-03-23,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,Florida,32216.0,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480
2017-10-02,CA-2017-118689,2017-10-09,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,Indiana,47905.0,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950
2018-03-23,CA-2018-140151,2018-03-25,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,Washington,98115.0,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960
2018-10-22,CA-2018-127180,2018-10-24,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,New York,10024.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968
2018-11-17,CA-2018-166709,2018-11-22,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,Delaware,19711.0,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970

### Observation

The IQR method identified 1145 potential outliers.

The detected outliers correspond to expensive technology products, such as enterprise copiers and video conferencing equipment. Since these transactions appear to be legitimate high-value sales and not data entry errors, they will be retained in the dataset for subsequent analysis.

## Save clean data

In [22]:
df.to_csv("../data/processed/clean_data.csv")